# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: r

r:
  - devel
  - release

r_build_args: --no-build-vignettes

os:
  - linux
  - osx

warnings_are_errors: false

jobs:
  exclude:
  - os: osx
    r: devel

r_packages:
  - Rcpp
  - transport
  - proxy
  - MASS
  - sampling
  - BalancedSampling
  - stats
  - utils
  - knitr
  - rmarkdown
  - ggplot2
  - ggvoronoi
  - lpSolve
  - sp
  - sf
  - stats
  - testthat