# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Binomial Coefficient
#'
#' @description
#' It calculates the number of sets with size \eqn{k} that can be chosen from a set of size \eqn{n}.
#'
#' @param n An integer. (greater than k)
#' @param k An integer.
#'
#' @return An integer "n choose k".
#'
#' @author Raphael Jauslin \email{raphael.jauslin@@unine.ch}
#'
#' @seealso
#' \code{\link[base:choose]{base::choose}}
#'
#' @examples
#' choose(10,5)
#' @export
choose <- function(n, k) {
    .Call(`_StratifiedSampling_choose`, n, k)
}

#' @title Disjunctive Vector
#'
#' @description
#' This function transform a categorical vector into a matrix of indicators.
#'
#' @param strata A vector of integer that represents the categories.
#'
#' @return A matrix of indicators.
#'
#' @author Raphaël Jauslin \email{raphael.jauslin@@unine.ch}
#'
#' @examples
#' strata <- rep(c(1,2,3),each = 4)
#' disj(strata)
#'
#' @export
disj <- function(strata) {
    .Call(`_StratifiedSampling_disj`, strata)
}

#' @title Number of categories
#'
#' @description
#' This function returns the number of factor in each column of a categorical matrix.
#'
#' @param Xcat A matrix of integer that contains categorical vector in each column.
#'
#' @return A row vector that contains the number of categories in each column.
#'
#' @author Raphaël Jauslin \email{raphael.jauslin@@unine.ch}
#'
#' @export
#' 
#' @examples
#' Xcat <-  matrix(c(sample(x = 1:6, size = 100, replace = TRUE),
#'             sample(x = 1:6, size = 100, replace = TRUE),
#'             sample(x = 1:6, size = 100, replace = TRUE)),ncol = 3)
#' ncat(Xcat)
ncat <- function(Xcat) {
    .Call(`_StratifiedSampling_ncat`, Xcat)
}

#' @title Disjunctive Matrix
#'
#' @description
#' This function transform a categorical matrix into a matrix of indicators variables.
#'
#' @param strata A matrix of integer that contains categorical vector in each column.
#'
#' @return A matrix of indicators.
#'
#' @author Raphaël Jauslin \email{raphael.jauslin@@unine.ch}
#' 
#' @examples
#' Xcat <-  matrix(c(sample(x = 1:6, size = 100, replace = TRUE),
#'             sample(x = 1:6, size = 100, replace = TRUE),
#'             sample(x = 1:6, size = 100, replace = TRUE)),ncol = 3)
#' disjMatrix(Xcat)
#'
#' @export
disjMatrix <- function(strata) {
    .Call(`_StratifiedSampling_disjMatrix`, strata)
}

#' @title Samples of fixed size 
#'
#' @description
#' Gives a matrix that contains in each column a possible sample of size \eqn{n}.
#'
#' @param N An integer, the size of the population
#' @param n An integer, the sample size.
#'
#' @details
#' It uses a fast implementation. See References.
#'
#' @return A matrix of indicator variables.
#'
#' @references \url{http://www.rosettacode.org/wiki/Rosetta_Code}
#' @author Raphaël Jauslin \email{raphael.jauslin@@unine.ch}
#'
#' @seealso
#' \code{\link{landingLP}}
#'
#' @examples
#' samplen(4,2)
#' 
#' @export
samplen <- function(N, n) {
    .Call(`_StratifiedSampling_samplen`, N, n)
}

